import { createSelector } from '@ngrx/store';
import { policyFeature } from './policy.reducer';

// All basic selectors are auto-generated by createFeature from PolicyState fields.
// selectSummaryStats is auto-generated from the summaryStats state field and is
// populated by the loadSummarySuccess action (not computed from paginated data).
export const {
  name: policyFeatureKey,
  reducer: policyReducer,
  selectPolicyState,
  selectPolicies,
  selectFilters,
  selectPagination,
  selectSort,
  selectSelectedPolicyIds,
  selectLoadStatus,
  selectError,
  selectSummaryStats,
} = policyFeature;

export const selectLoading = createSelector(
  selectLoadStatus,
  (loadStatus) => loadStatus === 'loading'
);

export const selectPoliciesByIds = createSelector(
  selectPolicies,
  selectSelectedPolicyIds,
  (policies, selectedIds) => policies.filter((p) => selectedIds.includes(p.id))
);
